# Generated by Django 2.2.7 on 2019-11-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20191121_0535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thisisatest',
            options={'verbose_name_plural': 'These are tests'},
        ),
    ]
