# Generated by Django 2.2.7 on 2019-11-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20191121_0542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='ThisIsATest',
        ),
    ]
